<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DebugType>Full</DebugType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
	  <!--<CoverletExcludeByAttribute>GeneratedCodeAttribute,CompilerGeneratedAttribute,ExcludeFromCodeCoverageAttribute</CoverletExcludeByAttribute>-->
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="bunit.web" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.MTP" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Shared" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EstateManagementUI.BlazorServer\EstateManagementUI.BlazorServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

	<!--<ItemGroup>
		--><!-- Exclude only .razor markup files, not .razor.cs code-behind files --><!--
		<CoverletExcludeByFile Include="**/*.razor" />
	</ItemGroup>-->

</Project>
