using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Microsoft.JSInterop;
using MediatR;
using Imposter.Abstractions;
using EstateManagementUI.BusinessLogic.Client;
using EstateManagementUI.BusinessLogic.Services;
using EstateManagementUI.BlazorServer.UIServices;
using EstateManagementUI.BlazorServer.Permissions;


[assembly: GenerateImposter(typeof(AuthenticationStateProvider))]
[assembly: GenerateImposter(typeof(IApiClient))]
[assembly: GenerateImposter(typeof(ICalendarUIService))]
[assembly: GenerateImposter(typeof(IContractUIService))]
[assembly: GenerateImposter(typeof(IEstateUIService))]
[assembly: GenerateImposter(typeof(IFileProcessingUIService))]
[assembly: GenerateImposter(typeof(IHttpContextAccessor))]
[assembly: GenerateImposter(typeof(IJSRuntime))]
[assembly: GenerateImposter(typeof(ILogger<>))]
[assembly: GenerateImposter(typeof(ILoggerFactory))]
[assembly: GenerateImposter(typeof(IMediator))]
[assembly: GenerateImposter(typeof(IMerchantUIService))]
[assembly: GenerateImposter(typeof(IOperatorUIService))]
[assembly: GenerateImposter(typeof(IOptionsMonitor<AuthenticationSchemeOptions>))]
[assembly: GenerateImposter(typeof(IPermissionKeyProvider))]
[assembly: GenerateImposter(typeof(IPermissionService))]
[assembly: GenerateImposter(typeof(IPermissionStore))]
[assembly: GenerateImposter(typeof(ISession))]
[assembly: GenerateImposter(typeof(ISessionFeature))]
[assembly: GenerateImposter(typeof(ITransactionUIService))]
[assembly: GenerateImposter(typeof(IWebHostEnvironment))]
[assembly: GenerateImposter(typeof(NavigationManager))]
