// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace EstateManagementUI.BlazorFastIntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("File Processing")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("base")]
    [global::NUnit.Framework.CategoryAttribute("background")]
    [global::NUnit.Framework.CategoryAttribute("estate")]
    [global::NUnit.Framework.CategoryAttribute("fileprocessing")]
    [global::NUnit.Framework.CategoryAttribute("dashboard")]
    public partial class FileProcessingFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "base",
                "background",
                "estate",
                "fileprocessing",
                "dashboard"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "File Processing", "  As an authenticated estate user\r\n  I want to upload a batch topup file\r\n  So th" +
                "at I can prove the upload flow works end to end", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "FileProcessing.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
  #line hidden
            global::Reqnroll.Table table37 = new global::Reqnroll.Table(new string[] {
                        "Role Name"});
            table37.AddRow(new string[] {
                        "Administrator"});
            table37.AddRow(new string[] {
                        "Estate"});
#line 8
    await testRunner.GivenAsync("I create the following roles", ((string)(null)), table37, "Given ");
#line hidden
            global::Reqnroll.Table table38 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Description"});
            table38.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST Scope",
                        "Scope for Transaction Processor REST"});
            table38.AddRow(new string[] {
                        "fileProcessor",
                        "File Processor REST Scope",
                        "Scope for File Processor REST"});
            table38.AddRow(new string[] {
                        "estateReporting",
                        "Estate Reporting REST Scope",
                        "Scope for Estate Reporting REST"});
#line 13
    await testRunner.GivenAsync("I create the following api scopes", ((string)(null)), table38, "Given ");
#line hidden
            global::Reqnroll.Table table39 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Secret",
                        "Scopes",
                        "UserClaims"});
            table39.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST",
                        "Secret1",
                        "transactionProcessor",
                        "merchantId,estateId,role"});
            table39.AddRow(new string[] {
                        "fileProcessor",
                        "File Processor REST",
                        "Secret1",
                        "fileProcessor",
                        "merchantId,estateId,role"});
            table39.AddRow(new string[] {
                        "estateReporting",
                        "Estate Reporting REST",
                        "Secret1",
                        "estateReporting",
                        "merchantId,estateId,role"});
#line 19
    await testRunner.GivenAsync("I create the following api resources", ((string)(null)), table39, "Given ");
#line hidden
            global::Reqnroll.Table table40 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Description",
                        "UserClaims"});
            table40.AddRow(new string[] {
                        "openid",
                        "Your user identifier",
                        "",
                        "sub"});
            table40.AddRow(new string[] {
                        "profile",
                        "User profile",
                        "Your user profile information (first name, last name, etc.)",
                        "name,role,email,given_name,middle_name,family_name,estateId,merchantId"});
            table40.AddRow(new string[] {
                        "email",
                        "Email",
                        "Email and Email Verified Flags",
                        "email_verified,email"});
#line 25
    await testRunner.GivenAsync("I create the following identity resources", ((string)(null)), table40, "Given ");
#line hidden
            global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                        "ClientId",
                        "Name",
                        "Secret",
                        "Scopes",
                        "GrantTypes",
                        "RedirectUris",
                        "PostLogoutRedirectUris",
                        "RequireConsent",
                        "AllowOfflineAccess",
                        "ClientUri"});
            table41.AddRow(new string[] {
                        "serviceClient",
                        "Service Client",
                        "Secret1",
                        "transactionProcessor,fileProcessor,estateReporting",
                        "client_credentials",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table41.AddRow(new string[] {
                        "estateUIClient",
                        "Merchant Client",
                        "Secret1",
                        "fileProcessor,transactionProcessor,estateReporting,openid,email,profile",
                        "hybrid",
                        "https://127.0.0.1:[port]/signin-oidc",
                        "https://127.0.0.1:[port]/signout-oidc",
                        "false",
                        "true",
                        "https://127.0.0.1:[port]"});
#line 31
    await testRunner.GivenAsync("I create the following clients", ((string)(null)), table41, "Given ");
#line hidden
            global::Reqnroll.Table table42 = new global::Reqnroll.Table(new string[] {
                        "Email Address",
                        "Phone Number",
                        "Given Name",
                        "Middle Name",
                        "Family Name",
                        "Claims",
                        "Roles",
                        "Password"});
            table42.AddRow(new string[] {
                        "administrator@admin.co.uk",
                        "123456789",
                        "Test",
                        "",
                        "User 1",
                        "",
                        "Administrator",
                        "123456"});
#line 36
    await testRunner.GivenAsync("I create the following users", ((string)(null)), table42, "Given ");
#line hidden
            global::Reqnroll.Table table43 = new global::Reqnroll.Table(new string[] {
                        "ClientId"});
            table43.AddRow(new string[] {
                        "serviceClient"});
#line 40
    await testRunner.GivenAsync("I have a token to access the transaction Processor resource", ((string)(null)), table43, "Given ");
#line hidden
            global::Reqnroll.Table table44 = new global::Reqnroll.Table(new string[] {
                        "EstateName"});
            table44.AddRow(new string[] {
                        "Test Estate"});
#line 44
    await testRunner.GivenAsync("I have created the following estates", ((string)(null)), table44, "Given ");
#line hidden
            global::Reqnroll.Table table45 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "RequireCustomMerchantNumber",
                        "RequireCustomTerminalNumber"});
            table45.AddRow(new string[] {
                        "Test Estate",
                        "Test Operator",
                        "True",
                        "True"});
#line 48
    await testRunner.AndAsync("I have created the following operators", ((string)(null)), table45, "And ");
#line hidden
            global::Reqnroll.Table table46 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName"});
            table46.AddRow(new string[] {
                        "Test Estate",
                        "Test Operator"});
#line 52
    await testRunner.AndAsync("I have assigned the following operators to the estates", ((string)(null)), table46, "And ");
#line hidden
            global::Reqnroll.Table table47 = new global::Reqnroll.Table(new string[] {
                        "EmailAddress",
                        "Password",
                        "GivenName",
                        "FamilyName",
                        "EstateName"});
            table47.AddRow(new string[] {
                        "estateuser@testestate1.co.uk",
                        "123456",
                        "TestEstate",
                        "User1",
                        "Test Estate"});
#line 56
    await testRunner.AndAsync("I have created the following security users", ((string)(null)), table47, "And ");
#line hidden
#line 60
    await testRunner.GivenAsync("the user navigates to the app address", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 61
    await testRunner.AndAsync("I click on the Sign In Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
    await testRunner.ThenAsync("I am presented with a login screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 63
    await testRunner.WhenAsync("I login with the username \'estateuser@testestate1.co.uk\' and password \'123456\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
    await testRunner.ThenAsync("I should see the dashboard heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            global::Reqnroll.Table table48 = new global::Reqnroll.Table(new string[] {
                        "MerchantName",
                        "SettlementSchedule",
                        "AddressLine1",
                        "AddressLine2",
                        "Town",
                        "Region",
                        "PostCode",
                        "Country",
                        "ContactName",
                        "EmailAddress",
                        "PhoneNumber"});
            table48.AddRow(new string[] {
                        "Test Merchant 1",
                        "Immediate",
                        "1 Integration Road",
                        "Suite 100",
                        "Test Town",
                        "Test Region",
                        "TE1 1ST",
                        "United Kingdom",
                        "Test Contact",
                        "test.contact@example.com",
                        "01234567890"});
#line 65
    await testRunner.AndAsync("I have created the following merchants", ((string)(null)), table48, "And ");
#line hidden
            global::Reqnroll.Table table49 = new global::Reqnroll.Table(new string[] {
                        "FileProfileId",
                        "Name",
                        "ListeningDirectory",
                        "RequestType",
                        "OperatorName",
                        "LineTerminator",
                        "FileFormatHandler"});
            table49.AddRow(new string[] {
                        "11111111-1111-1111-1111-111111111111",
                        "SafaricomTopup",
                        "/tmp",
                        "BatchTopup",
                        "Test Operator",
                        "CarriageReturnLineFeed",
                        "CsvFileFormatHandler"});
#line 68
    await testRunner.AndAsync("I have created the following file profiles", ((string)(null)), table49, "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/FileProcessing.feature.ndjson", 3);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Estate users can upload a batch topup file successfully")]
        public async global::System.Threading.Tasks.Task EstateUsersCanUploadABatchTopupFileSuccessfully()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Estate users can upload a batch topup file successfully", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 72
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 73
    await testRunner.WhenAsync("I open the file processing screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
    await testRunner.ThenAsync("I should see the file processing heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 75
    await testRunner.WhenAsync("I open the file upload page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 76
    await testRunner.ThenAsync("I should see the file upload page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 77
    await testRunner.AndAsync("the upload dropdowns should default to the placeholder option", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table50 = new global::Reqnroll.Table(new string[] {
                            "PhoneNumber",
                            "Amount"});
                table50.AddRow(new string[] {
                            "254701000001",
                            "500"});
                table50.AddRow(new string[] {
                            "254701000002",
                            "500"});
                table50.AddRow(new string[] {
                            "254701000003",
                            "500"});
#line 78
    await testRunner.WhenAsync("I upload a batch topup file", ((string)(null)), table50, "When ");
#line hidden
#line 83
    await testRunner.ThenAsync("I should see the upload success message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
