// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace EstateManagementUI.BlazorFastIntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Merchant Management")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("base")]
    [global::NUnit.Framework.CategoryAttribute("background")]
    [global::NUnit.Framework.CategoryAttribute("dashboard")]
    [global::NUnit.Framework.CategoryAttribute("estate")]
    public partial class MerchantManagementFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "base",
                "background",
                "dashboard",
                "estate"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Merchant Management", "  As an authenticated estate user\r\n  I want to move through the merchant manageme" +
                "nt screens\r\n  So that I can create, inspect, edit, schedule, and deposit against" +
                " a merchant from one journey", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "MerchantManagement.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
  #line hidden
            global::Reqnroll.Table table51 = new global::Reqnroll.Table(new string[] {
                        "Role Name"});
            table51.AddRow(new string[] {
                        "Administrator"});
            table51.AddRow(new string[] {
                        "Estate"});
#line 8
    await testRunner.GivenAsync("I create the following roles", ((string)(null)), table51, "Given ");
#line hidden
            global::Reqnroll.Table table52 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Description"});
            table52.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST Scope",
                        "Scope for Transaction Processor REST"});
            table52.AddRow(new string[] {
                        "fileProcessor",
                        "File Processor REST Scope",
                        "Scope for File Processor REST"});
            table52.AddRow(new string[] {
                        "estateReporting",
                        "Estate Reporting REST Scope",
                        "Scope for Estate Reporting REST"});
#line 13
    await testRunner.GivenAsync("I create the following api scopes", ((string)(null)), table52, "Given ");
#line hidden
            global::Reqnroll.Table table53 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Secret",
                        "Scopes",
                        "UserClaims"});
            table53.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST",
                        "Secret1",
                        "transactionProcessor",
                        "merchantId,estateId,role"});
            table53.AddRow(new string[] {
                        "fileProcessor",
                        "File Processor REST",
                        "Secret1",
                        "fileProcessor",
                        "merchantId,estateId,role"});
            table53.AddRow(new string[] {
                        "estateReporting",
                        "Estate Reporting REST",
                        "Secret1",
                        "estateReporting",
                        "merchantId,estateId,role"});
#line 19
    await testRunner.GivenAsync("I create the following api resources", ((string)(null)), table53, "Given ");
#line hidden
            global::Reqnroll.Table table54 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Description",
                        "UserClaims"});
            table54.AddRow(new string[] {
                        "openid",
                        "Your user identifier",
                        "",
                        "sub"});
            table54.AddRow(new string[] {
                        "profile",
                        "User profile",
                        "Your user profile information (first name, last name, etc.)",
                        "name,role,email,given_name,middle_name,family_name,estateId,merchantId"});
            table54.AddRow(new string[] {
                        "email",
                        "Email",
                        "Email and Email Verified Flags",
                        "email_verified,email"});
#line 25
    await testRunner.GivenAsync("I create the following identity resources", ((string)(null)), table54, "Given ");
#line hidden
            global::Reqnroll.Table table55 = new global::Reqnroll.Table(new string[] {
                        "ClientId",
                        "Name",
                        "Secret",
                        "Scopes",
                        "GrantTypes",
                        "RedirectUris",
                        "PostLogoutRedirectUris",
                        "RequireConsent",
                        "AllowOfflineAccess",
                        "ClientUri"});
            table55.AddRow(new string[] {
                        "serviceClient",
                        "Service Client",
                        "Secret1",
                        "transactionProcessor,fileProcessor,estateReporting",
                        "client_credentials",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table55.AddRow(new string[] {
                        "estateUIClient",
                        "Merchant Client",
                        "Secret1",
                        "fileProcessor,transactionProcessor,estateReporting,openid,email,profile",
                        "hybrid",
                        "https://127.0.0.1:[port]/signin-oidc",
                        "https://127.0.0.1:[port]/signout-oidc",
                        "false",
                        "true",
                        "https://127.0.0.1:[port]"});
#line 31
    await testRunner.GivenAsync("I create the following clients", ((string)(null)), table55, "Given ");
#line hidden
            global::Reqnroll.Table table56 = new global::Reqnroll.Table(new string[] {
                        "Email Address",
                        "Phone Number",
                        "Given Name",
                        "Middle Name",
                        "Family Name",
                        "Claims",
                        "Roles",
                        "Password"});
            table56.AddRow(new string[] {
                        "administrator@admin.co.uk",
                        "123456789",
                        "Test",
                        "",
                        "User 1",
                        "",
                        "Administrator",
                        "123456"});
#line 36
    await testRunner.GivenAsync("I create the following users", ((string)(null)), table56, "Given ");
#line hidden
            global::Reqnroll.Table table57 = new global::Reqnroll.Table(new string[] {
                        "ClientId"});
            table57.AddRow(new string[] {
                        "serviceClient"});
#line 40
    await testRunner.GivenAsync("I have a token to access the transaction Processor resource", ((string)(null)), table57, "Given ");
#line hidden
            global::Reqnroll.Table table58 = new global::Reqnroll.Table(new string[] {
                        "EstateName"});
            table58.AddRow(new string[] {
                        "Test Estate"});
#line 44
    await testRunner.GivenAsync("I have created the following estates", ((string)(null)), table58, "Given ");
#line hidden
            global::Reqnroll.Table table59 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "RequireCustomMerchantNumber",
                        "RequireCustomTerminalNumber"});
            table59.AddRow(new string[] {
                        "Test Estate",
                        "Test Operator",
                        "True",
                        "True"});
#line 48
    await testRunner.AndAsync("I have created the following operators", ((string)(null)), table59, "And ");
#line hidden
            global::Reqnroll.Table table60 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName"});
            table60.AddRow(new string[] {
                        "Test Estate",
                        "Test Operator"});
#line 52
    await testRunner.AndAsync("I have assigned the following operators to the estates", ((string)(null)), table60, "And ");
#line hidden
            global::Reqnroll.Table table61 = new global::Reqnroll.Table(new string[] {
                        "EmailAddress",
                        "Password",
                        "GivenName",
                        "FamilyName",
                        "EstateName"});
            table61.AddRow(new string[] {
                        "estateuser@testestate1.co.uk",
                        "123456",
                        "TestEstate",
                        "User1",
                        "Test Estate"});
#line 56
    await testRunner.AndAsync("I have created the following security users", ((string)(null)), table61, "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/MerchantManagement.feature.ndjson", 3);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Estate users can complete the full merchant screen flow")]
        public async global::System.Threading.Tasks.Task EstateUsersCanCompleteTheFullMerchantScreenFlow()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Estate users can complete the full merchant screen flow", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 61
    await testRunner.GivenAsync("the user navigates to the app address", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
    await testRunner.AndAsync("I click on the Sign In Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
    await testRunner.ThenAsync("I am presented with a login screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 64
    await testRunner.WhenAsync("I login with the username \'estateuser@testestate1.co.uk\' and password \'123456\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
    await testRunner.ThenAsync("I should see the dashboard heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 66
    await testRunner.WhenAsync("I open the merchant management screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
    await testRunner.ThenAsync("I should see the merchant management heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table62 = new global::Reqnroll.Table(new string[] {
                            "MerchantName",
                            "SettlementSchedule",
                            "AddressLine1",
                            "AddressLine2",
                            "Town",
                            "Region",
                            "PostCode",
                            "Country",
                            "ContactName",
                            "EmailAddress",
                            "PhoneNumber"});
                table62.AddRow(new string[] {
                            "Integration Merchant 1",
                            "Immediate",
                            "1 Integration Road",
                            "Suite 100",
                            "Test Town",
                            "Test Region",
                            "TE1 1ST",
                            "United Kingdom",
                            "Test Contact",
                            "test.contact@example.com",
                            "01234567890"});
#line 68
    await testRunner.WhenAsync("I create the following merchants", ((string)(null)), table62, "When ");
#line hidden
#line 71
    await testRunner.ThenAsync("I should see the merchant in the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
    await testRunner.WhenAsync("I view the merchant", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
    await testRunner.ThenAsync("I should see the merchant view page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 74
    await testRunner.WhenAsync("I switch to the address tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 75
    await testRunner.ThenAsync("I should see the merchant address details", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 76
    await testRunner.WhenAsync("I switch to the contact tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 77
    await testRunner.ThenAsync("I should see the merchant contact details", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 78
    await testRunner.WhenAsync("I switch to the opening hours tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
    await testRunner.ThenAsync("I should see the merchant opening hours details", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 80
    await testRunner.WhenAsync("I switch to the merchant operators tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
    await testRunner.ThenAsync("I should see no operators assigned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
    await testRunner.WhenAsync("I switch to the contracts tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
    await testRunner.ThenAsync("I should see no contracts assigned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 84
    await testRunner.WhenAsync("I switch to the devices tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 85
    await testRunner.ThenAsync("I should see no devices assigned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 86
    await testRunner.WhenAsync("I open the merchant schedule from the view page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 87
    await testRunner.ThenAsync("I should see the read-only merchant schedule page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 88
    await testRunner.WhenAsync("I return to the merchant view page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
    await testRunner.ThenAsync("I should see the merchant view page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 90
    await testRunner.WhenAsync("I open the merchant edit page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 91
    await testRunner.ThenAsync("I should see the merchant edit page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 92
    await testRunner.WhenAsync("I switch to the opening hours editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 93
    await testRunner.ThenAsync("I should see the merchant opening hours editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table63 = new global::Reqnroll.Table(new string[] {
                            "MondayOpening",
                            "MondayClosing",
                            "TuesdayOpening",
                            "TuesdayClosing",
                            "WednesdayOpening",
                            "WednesdayClosing",
                            "ThursdayOpening",
                            "ThursdayClosing",
                            "FridayOpening",
                            "FridayClosing",
                            "SaturdayOpening",
                            "SaturdayClosing",
                            "SundayOpening",
                            "SundayClosing"});
                table63.AddRow(new string[] {
                            "0800",
                            "1700",
                            "0800",
                            "1700",
                            "0800",
                            "1700",
                            "0800",
                            "1700",
                            "0800",
                            "1700",
                            "0900",
                            "1600",
                            "1000",
                            "1500"});
#line 94
    await testRunner.WhenAsync("I save merchant opening hours", ((string)(null)), table63, "When ");
#line hidden
#line 97
    await testRunner.ThenAsync("I should see merchant opening hours updated successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 98
    await testRunner.WhenAsync("I switch to the merchant operators editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table64 = new global::Reqnroll.Table(new string[] {
                            "OperatorName",
                            "MerchantNumber",
                            "TerminalNumber"});
                table64.AddRow(new string[] {
                            "Test Operator",
                            "12345678",
                            "87654321"});
#line 99
    await testRunner.AndAsync("I add the operator to the merchant", ((string)(null)), table64, "And ");
#line hidden
#line 102
    await testRunner.ThenAsync("I should see the operator in the merchant list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 103
    await testRunner.WhenAsync("I switch to the contracts editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 104
    await testRunner.ThenAsync("I should see no contracts assigned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 105
    await testRunner.WhenAsync("I switch to the devices editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table65 = new global::Reqnroll.Table(new string[] {
                            "DeviceIdentifier"});
                table65.AddRow(new string[] {
                            "DEVICE-001"});
#line 106
    await testRunner.AndAsync("I add the device to the merchant", ((string)(null)), table65, "And ");
#line hidden
#line 109
    await testRunner.ThenAsync("I should see the device in the merchant list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 110
    await testRunner.WhenAsync("I open the merchant schedule from the edit page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 111
    await testRunner.ThenAsync("I should see the editable merchant schedule page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table66 = new global::Reqnroll.Table(new string[] {
                            "Year",
                            "ClosedDays"});
                table66.AddRow(new string[] {
                            "2027",
                            "1, 2, 15"});
#line 112
    await testRunner.WhenAsync("I save the merchant schedule", ((string)(null)), table66, "When ");
#line hidden
#line 115
    await testRunner.ThenAsync("I should see schedule saved successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 116
    await testRunner.WhenAsync("I return to the merchant edit page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 117
    await testRunner.ThenAsync("I should see the merchant edit page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 118
    await testRunner.WhenAsync("I open the merchant deposit page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 119
    await testRunner.ThenAsync("I should see the merchant deposit page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table67 = new global::Reqnroll.Table(new string[] {
                            "Amount",
                            "Date",
                            "Reference"});
                table67.AddRow(new string[] {
                            "100",
                            "2026-07-22",
                            "DEP-001"});
#line 120
    await testRunner.WhenAsync("I submit the merchant deposit", ((string)(null)), table67, "When ");
#line hidden
#line 123
    await testRunner.ThenAsync("I should be back on the merchant list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
