// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace EstateManagementUI.BlazorFastIntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Reporting")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("base")]
    [global::NUnit.Framework.CategoryAttribute("background")]
    [global::NUnit.Framework.CategoryAttribute("reporting")]
    [global::NUnit.Framework.CategoryAttribute("dashboard")]
    public partial class ReportingFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "base",
                "background",
                "reporting",
                "dashboard"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Reporting", "  As an authenticated estate user\r\n  I want to inspect the reporting screens\r\n  S" +
                "o that I can verify the key report pages still work without Docker-backed setup", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Reporting.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
  #line hidden
            global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                        "Role Name"});
            table1.AddRow(new string[] {
                        "Administrator"});
            table1.AddRow(new string[] {
                        "Estate"});
#line 8
    await testRunner.GivenAsync("I create the following roles", ((string)(null)), table1, "Given ");
#line hidden
            global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Description"});
            table2.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST Scope",
                        "Scope for Transaction Processor REST"});
            table2.AddRow(new string[] {
                        "fileProcessor",
                        "File Processor REST Scope",
                        "Scope for File Processor REST"});
            table2.AddRow(new string[] {
                        "estateReporting",
                        "Estate Reporting REST Scope",
                        "Scope for Estate Reporting REST"});
#line 13
    await testRunner.AndAsync("I create the following api scopes", ((string)(null)), table2, "And ");
#line hidden
            global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Secret",
                        "Scopes",
                        "UserClaims"});
            table3.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST",
                        "Secret1",
                        "transactionProcessor",
                        "merchantId,estateId,role"});
            table3.AddRow(new string[] {
                        "fileProcessor",
                        "File Processor REST",
                        "Secret1",
                        "fileProcessor",
                        "merchantId,estateId,role"});
            table3.AddRow(new string[] {
                        "estateReporting",
                        "Estate Reporting REST",
                        "Secret1",
                        "estateReporting",
                        "merchantId,estateId,role"});
#line 19
    await testRunner.AndAsync("I create the following api resources", ((string)(null)), table3, "And ");
#line hidden
            global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Description",
                        "UserClaims"});
            table4.AddRow(new string[] {
                        "openid",
                        "Your user identifier",
                        "",
                        "sub"});
            table4.AddRow(new string[] {
                        "profile",
                        "User profile",
                        "Your user profile information (first name, last name, etc.)",
                        "name,role,email,given_name,middle_name,family_name,estateId,merchantId"});
            table4.AddRow(new string[] {
                        "email",
                        "Email",
                        "Email and Email Verified Flags",
                        "email_verified,email"});
#line 25
    await testRunner.AndAsync("I create the following identity resources", ((string)(null)), table4, "And ");
#line hidden
            global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                        "ClientId",
                        "Name",
                        "Secret",
                        "Scopes",
                        "GrantTypes",
                        "RedirectUris",
                        "PostLogoutRedirectUris",
                        "RequireConsent",
                        "AllowOfflineAccess",
                        "ClientUri"});
            table5.AddRow(new string[] {
                        "serviceClient",
                        "Service Client",
                        "Secret1",
                        "transactionProcessor,fileProcessor,estateReporting",
                        "client_credentials",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table5.AddRow(new string[] {
                        "estateUIClient",
                        "Merchant Client",
                        "Secret1",
                        "fileProcessor,transactionProcessor,estateReporting,openid,email,profile",
                        "hybrid",
                        "https://127.0.0.1:[port]/signin-oidc",
                        "https://127.0.0.1:[port]/signout-oidc",
                        "false",
                        "true",
                        "https://127.0.0.1:[port]"});
#line 31
    await testRunner.AndAsync("I create the following clients", ((string)(null)), table5, "And ");
#line hidden
            global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                        "Email Address",
                        "Phone Number",
                        "Given Name",
                        "Middle Name",
                        "Family Name",
                        "Claims",
                        "Roles",
                        "Password"});
            table6.AddRow(new string[] {
                        "administrator@admin.co.uk",
                        "123456789",
                        "Test",
                        "",
                        "User 1",
                        "",
                        "Administrator",
                        "123456"});
#line 36
    await testRunner.AndAsync("I create the following users", ((string)(null)), table6, "And ");
#line hidden
            global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                        "ClientId"});
            table7.AddRow(new string[] {
                        "serviceClient"});
#line 40
    await testRunner.AndAsync("I have a token to access the transaction Processor resource", ((string)(null)), table7, "And ");
#line hidden
            global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                        "EstateName"});
            table8.AddRow(new string[] {
                        "Test Estate"});
#line 44
    await testRunner.AndAsync("I have created the following estates", ((string)(null)), table8, "And ");
#line hidden
            global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "RequireCustomMerchantNumber",
                        "RequireCustomTerminalNumber"});
            table9.AddRow(new string[] {
                        "Test Estate",
                        "Test Operator",
                        "True",
                        "True"});
#line 48
    await testRunner.AndAsync("I have created the following operators", ((string)(null)), table9, "And ");
#line hidden
            global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName"});
            table10.AddRow(new string[] {
                        "Test Estate",
                        "Test Operator"});
#line 52
    await testRunner.AndAsync("I have assigned the following operators to the estates", ((string)(null)), table10, "And ");
#line hidden
            global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                        "EmailAddress",
                        "Password",
                        "GivenName",
                        "FamilyName",
                        "EstateName"});
            table11.AddRow(new string[] {
                        "estateuser@testestate1.co.uk",
                        "123456",
                        "TestEstate",
                        "User1",
                        "Test Estate"});
#line 56
    await testRunner.AndAsync("I have created the following security users", ((string)(null)), table11, "And ");
#line hidden
#line 60
    await testRunner.AndAsync("the user navigates to the app address", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
    await testRunner.AndAsync("I click on the Sign In Button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
    await testRunner.ThenAsync("I am presented with a login screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 63
    await testRunner.WhenAsync("I login with the username \'estateuser@testestate1.co.uk\' and password \'123456\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
    await testRunner.ThenAsync("I should see the dashboard heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Reporting.feature.ndjson", 11);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Reporting dashboard exposes all report links")]
        public async global::System.Threading.Tasks.Task ReportingDashboardExposesAllReportLinks()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reporting dashboard exposes all report links", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 66
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 67
    await testRunner.WhenAsync("I open the reporting dashboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 68
    await testRunner.ThenAsync("I should see the reporting dashboard heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 69
    await testRunner.AndAsync("I should see the reporting dashboard links", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Settlement summary report still renders the placeholder state")]
        public async global::System.Threading.Tasks.Task SettlementSummaryReportStillRendersThePlaceholderState()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Settlement summary report still renders the placeholder state", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 71
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 72
    await testRunner.WhenAsync("I open the settlement summary report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
    await testRunner.ThenAsync("I should see the settlement summary report heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 74
    await testRunner.AndAsync("I should see the settlement summary placeholder", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Merchant settlement history report still renders the placeholder state")]
        public async global::System.Threading.Tasks.Task MerchantSettlementHistoryReportStillRendersThePlaceholderState()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Merchant settlement history report still renders the placeholder state", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 76
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 77
    await testRunner.WhenAsync("I open the merchant settlement history report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 78
    await testRunner.ThenAsync("I should see the merchant settlement history report heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 79
    await testRunner.AndAsync("I should see the merchant settlement history placeholder", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Settlement reconciliation report still renders the placeholder state")]
        public async global::System.Threading.Tasks.Task SettlementReconciliationReportStillRendersThePlaceholderState()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Settlement reconciliation report still renders the placeholder state", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 81
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 82
    await testRunner.WhenAsync("I open the settlement reconciliation report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
    await testRunner.ThenAsync("I should see the settlement reconciliation report heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 84
    await testRunner.AndAsync("I should see the settlement reconciliation placeholder", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Transaction detail report shows the seeded sales")]
        public async global::System.Threading.Tasks.Task TransactionDetailReportShowsTheSeededSales()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Transaction detail report shows the seeded sales", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 86
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 87
    await testRunner.WhenAsync("I open the transaction detail report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 88
    await testRunner.ThenAsync("I should see the transaction detail report heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Label",
                            "Value"});
                table12.AddRow(new string[] {
                            "Total Transactions",
                            "5"});
                table12.AddRow(new string[] {
                            "Gross Amount",
                            "50.00"});
                table12.AddRow(new string[] {
                            "Total Fees",
                            "6.25"});
                table12.AddRow(new string[] {
                            "Net Amount",
                            "43.75"});
#line 89
    await testRunner.AndAsync("the transaction detail report should show these summary values", ((string)(null)), table12, "And ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Transaction Number",
                            "Merchant",
                            "Product",
                            "Type",
                            "Status"});
                table13.AddRow(new string[] {
                            "1001",
                            "Reporting Merchant A",
                            "Reporting Product A",
                            "sale",
                            "Successful"});
                table13.AddRow(new string[] {
                            "1002",
                            "Reporting Merchant A",
                            "Reporting Product A",
                            "sale",
                            "Successful"});
                table13.AddRow(new string[] {
                            "1003",
                            "Reporting Merchant B",
                            "Reporting Product B",
                            "sale",
                            "Successful"});
                table13.AddRow(new string[] {
                            "1004",
                            "Reporting Merchant A",
                            "Reporting Product A",
                            "sale",
                            "Successful"});
                table13.AddRow(new string[] {
                            "1005",
                            "Reporting Merchant B",
                            "Reporting Product B",
                            "sale",
                            "Successful"});
#line 95
    await testRunner.AndAsync("the transaction detail report should list these transactions", ((string)(null)), table13, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Transaction summary by merchant aggregates seeded sales")]
        public async global::System.Threading.Tasks.Task TransactionSummaryByMerchantAggregatesSeededSales()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Transaction summary by merchant aggregates seeded sales", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 103
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 104
    await testRunner.WhenAsync("I open the transaction summary by merchant report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 105
    await testRunner.ThenAsync("I should see the transaction summary by merchant report heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "Label",
                            "Value"});
                table14.AddRow(new string[] {
                            "Total Merchants",
                            "2"});
                table14.AddRow(new string[] {
                            "Total Transactions",
                            "5"});
                table14.AddRow(new string[] {
                            "Total Value",
                            "50.00"});
                table14.AddRow(new string[] {
                            "Average Transaction",
                            "10.00"});
#line 106
    await testRunner.AndAsync("the merchant summary report should show these summary values", ((string)(null)), table14, "And ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Merchant",
                            "Total Count",
                            "Total Value",
                            "Average Value",
                            "Successful",
                            "Failed",
                            "Success Rate"});
                table15.AddRow(new string[] {
                            "Reporting Merchant A",
                            "3",
                            "30.00",
                            "10.00",
                            "3",
                            "0",
                            "10000.0"});
                table15.AddRow(new string[] {
                            "Reporting Merchant B",
                            "2",
                            "20.00",
                            "10.00",
                            "2",
                            "0",
                            "10000.0"});
#line 112
    await testRunner.AndAsync("the merchant summary report should list these merchant rows", ((string)(null)), table15, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Transaction summary by operator aggregates seeded sales")]
        public async global::System.Threading.Tasks.Task TransactionSummaryByOperatorAggregatesSeededSales()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Transaction summary by operator aggregates seeded sales", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 117
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 118
    await testRunner.WhenAsync("I open the transaction summary by operator report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 119
    await testRunner.ThenAsync("I should see the transaction summary by operator report heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "Label",
                            "Value"});
                table16.AddRow(new string[] {
                            "Total Operators",
                            "2"});
                table16.AddRow(new string[] {
                            "Total Transactions",
                            "5"});
                table16.AddRow(new string[] {
                            "Total Value",
                            "50.00"});
                table16.AddRow(new string[] {
                            "Average Transaction",
                            "10.00"});
#line 120
    await testRunner.AndAsync("the operator summary report should show these summary values", ((string)(null)), table16, "And ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "Operator",
                            "Transaction Count",
                            "Transaction Value",
                            "Average Value",
                            "Successful",
                            "Failed",
                            "Success Rate"});
                table17.AddRow(new string[] {
                            "Safaricom",
                            "3",
                            "30.00",
                            "10.00",
                            "3",
                            "0",
                            "10000.0"});
                table17.AddRow(new string[] {
                            "Voucher",
                            "2",
                            "20.00",
                            "10.00",
                            "2",
                            "0",
                            "10000.0"});
#line 126
    await testRunner.AndAsync("the operator summary report should list these operator rows", ((string)(null)), table17, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Product performance report shows the seeded product split")]
        public async global::System.Threading.Tasks.Task ProductPerformanceReportShowsTheSeededProductSplit()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Product performance report shows the seeded product split", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 131
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 132
    await testRunner.WhenAsync("I open the product performance report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 133
    await testRunner.ThenAsync("I should see the product performance report heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "Label",
                            "Value"});
                table18.AddRow(new string[] {
                            "Total Products",
                            "2"});
                table18.AddRow(new string[] {
                            "Total Transactions",
                            "5"});
                table18.AddRow(new string[] {
                            "Total Value",
                            "50.00"});
                table18.AddRow(new string[] {
                            "Average per Product",
                            "25.00"});
#line 134
    await testRunner.AndAsync("the product performance report should show these summary values", ((string)(null)), table18, "And ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "Product",
                            "Transaction Count",
                            "Transaction Value",
                            "Percentage"});
                table19.AddRow(new string[] {
                            "Reporting Product A",
                            "3",
                            "30.00",
                            "60.00"});
                table19.AddRow(new string[] {
                            "Reporting Product B",
                            "2",
                            "20.00",
                            "40.00"});
#line 140
    await testRunner.AndAsync("the product performance report should list these product rows", ((string)(null)), table19, "And ");
#line hidden
#line 144
    await testRunner.AndAsync("the product performance report should validate the percentage split", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Analytical charts report shows seeded count and value data")]
        public async global::System.Threading.Tasks.Task AnalyticalChartsReportShowsSeededCountAndValueData()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Analytical charts report shows seeded count and value data", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 146
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 147
    await testRunner.WhenAsync("I open the analytical charts report", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 148
    await testRunner.ThenAsync("I should see the analytical charts report heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "Label",
                            "Value"});
                table20.AddRow(new string[] {
                            "Total Count",
                            "523"});
                table20.AddRow(new string[] {
                            "Total Value",
                            "145000.00"});
                table20.AddRow(new string[] {
                            "Average Value",
                            "277.25"});
                table20.AddRow(new string[] {
                            "Net Settlement",
                            "30.00"});
#line 149
    await testRunner.AndAsync("the analytical charts report should show these summary values", ((string)(null)), table20, "And ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "Comparison Date"});
                table21.AddRow(new string[] {
                            "Yesterday"});
#line 155
    await testRunner.AndAsync("the analytical charts report should use this comparison date", ((string)(null)), table21, "And ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "Chart",
                            "Today",
                            "Comparison"});
                table22.AddRow(new string[] {
                            "Volume",
                            "3",
                            "2"});
                table22.AddRow(new string[] {
                            "Value",
                            "30.00",
                            "20.00"});
#line 158
    await testRunner.AndAsync("the analytical charts report should compare these chart totals", ((string)(null)), table22, "And ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "Chart",
                            "Hour",
                            "Today",
                            "Comparison"});
                table23.AddRow(new string[] {
                            "Volume",
                            "09:00",
                            "1",
                            "0"});
                table23.AddRow(new string[] {
                            "Volume",
                            "10:00",
                            "0",
                            "1"});
                table23.AddRow(new string[] {
                            "Volume",
                            "13:00",
                            "1",
                            "0"});
                table23.AddRow(new string[] {
                            "Volume",
                            "14:00",
                            "0",
                            "1"});
                table23.AddRow(new string[] {
                            "Volume",
                            "15:00",
                            "1",
                            "0"});
                table23.AddRow(new string[] {
                            "Value",
                            "09:00",
                            "10.00",
                            "0.00"});
                table23.AddRow(new string[] {
                            "Value",
                            "10:00",
                            "0.00",
                            "10.00"});
                table23.AddRow(new string[] {
                            "Value",
                            "13:00",
                            "10.00",
                            "0.00"});
                table23.AddRow(new string[] {
                            "Value",
                            "14:00",
                            "0.00",
                            "10.00"});
                table23.AddRow(new string[] {
                            "Value",
                            "15:00",
                            "10.00",
                            "0.00"});
#line 162
    await testRunner.AndAsync("the analytical charts report should compare these hourly chart points", ((string)(null)), table23, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
