// <auto-generated />
using EstateManagementUI.BusinessLogic.PermissionService.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstateManagementUI.BusinessLogic.Migrations
{
    [DbContext(typeof(PermissionsContext))]
    [Migration("20240806102152_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("EstateManagementUI.BusinessLogic.PermissionService.Database.Entities.ApplicationSection", b =>
                {
                    b.Property<int>("ApplicationSectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationSectionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ApplicationSections");
                });

            modelBuilder.Entity("EstateManagementUI.BusinessLogic.PermissionService.Database.Entities.Function", b =>
                {
                    b.Property<int>("FunctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicationSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FunctionId");

                    b.HasIndex("ApplicationSectionId", "Name")
                        .IsUnique();

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("EstateManagementUI.BusinessLogic.PermissionService.Database.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EstateManagementUI.BusinessLogic.PermissionService.Database.Entities.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RolePermissionId");

                    b.ToTable("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
