name: Nightly Build

on:
  schedule:
  - cron: "45 22 * * *"
  repository_dispatch:

jobs:
  unittests:
    name: "Nightly Build and Unit Test"

    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Restore Nuget Packages
      run: dotnet restore EstateManagementUI.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }}

    - name: Build Code
      run: |
        dotnet build EstateManagementUI.sln --configuration Release

    - name: Run Unit Tests
      run: |        
        dotnet test "EstateManagementUI.BusinessLogic.Tests\EstateManagementUI.BusinessLogic.Tests.csproj" /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:ExcludeByAttribute="Obsolete" /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByAttribute="CompilerGeneratedAttribute" /p:ExcludeByAttribute="ExcludeFromCodeCoverageAttribute" /p:CoverletOutput="../lcov1.info" /maxcpucount:1 /p:CoverletOutputFormat="lcov"
        dotnet test "EstateManagementUI.UITests\EstateManagementUI.UITests.csproj"   /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:ExcludeByAttribute="Obsolete" /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByAttribute="CompilerGeneratedAttribute" /p:ExcludeByAttribute="ExcludeFromCodeCoverageAttribute" /p:CoverletOutput="../lcov2.info" /maxcpucount:1 /p:CoverletOutputFormat="lcov"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3  
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
        files: ./lcov1.info,./lcov2.info

  chrometests:
    name: "Nightly Build - Chrome"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"
        NODE_VERSION: '14.x'                # set this to the node version to use

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Trust Certificate
      run: |
        sudo apt-get install expect
        certPath="$GITHUB_WORKSPACE/Certificates/aspnetapp-root-cert.pfx"
        password="password"

        # Use expect to automate the passphrase input
        expect -c "
        spawn openssl pkcs12 -in \"$certPath\" -clcerts -nokeys -out certificate.crt -password pass:\"$password\"
        expect \"Enter Import Password:\" { send \"$password\n\" }
        expect eof
        "

        expect -c "
        spawn openssl pkcs12 -in \"$certPath\" -nocerts -out private.key -password pass:\"$password\"
        expect \"Enter Import Password:\" { send \"$password\n\" }
        expect eof
        "

        sudo cp certificate.crt /usr/local/share/ca-certificates/aspnetapp-root-cert.crt
        sudo update-ca-certificates

        sudo cp private.key /etc/ssl/private/aspnetapp-root-cert.key
        sudo chmod 400 /etc/ssl/private/aspnetapp-root-cert.key    
            
    - name: Build Docker Image
      run: docker build . --file EstateManagementUI/Dockerfile --tag estatemanagementui:latest

    - name: Restore Nuget Packages
      run: dotnet restore EstateManagementUI.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }}

    - name: Run Integration Tests (Chrome)
      env:
        Browser: Chrome
        IsCI: true
      run: dotnet test "EstateManagementUI.IntegrationTests\EstateManagementUI.IntegrationTests.csproj" --filter Category=PRTest
      
    - uses: actions/upload-artifact@v4.4.0
      if: ${{ failure() }}
      with:
        name: chrometracelogs
        path: /home/txnproc/trace/   

  edgetests:
    name: "Nightly Build - Edge"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"
        NODE_VERSION: '14.x'                # set this to the node version to use

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Trust Certificate
      run: |
        sudo apt-get install expect
        certPath="$GITHUB_WORKSPACE/Certificates/aspnetapp-root-cert.pfx"
        password="password"

        # Use expect to automate the passphrase input
        expect -c "
        spawn openssl pkcs12 -in \"$certPath\" -clcerts -nokeys -out certificate.crt -password pass:\"$password\"
        expect \"Enter Import Password:\" { send \"$password\n\" }
        expect eof
        "

        expect -c "
        spawn openssl pkcs12 -in \"$certPath\" -nocerts -out private.key -password pass:\"$password\"
        expect \"Enter Import Password:\" { send \"$password\n\" }
        expect eof
        "

        sudo cp certificate.crt /usr/local/share/ca-certificates/aspnetapp-root-cert.crt
        sudo update-ca-certificates

        sudo cp private.key /etc/ssl/private/aspnetapp-root-cert.key
        sudo chmod 400 /etc/ssl/private/aspnetapp-root-cert.key    
            
    - name: Build Docker Image
      run: docker build . --file EstateManagementUI/Dockerfile --tag estatemanagementui:latest

    - name: Restore Nuget Packages
      run: dotnet restore EstateManagementUI.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }}

    - name: Run Integration Tests (Edge)
      env:
        Browser: Edge
        IsCI: true
      run: dotnet test "EstateManagementUI.IntegrationTests\EstateManagementUI.IntegrationTests.csproj" --filter Category=PRTest
      
    - uses: actions/upload-artifact@v4.4.0
      if: ${{ failure() }}
      with:
        name: edgetracelogs
        path: /home/txnproc/trace/   

  fireefoxtests:
    name: "Nightly Build - Firefox"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"
        NODE_VERSION: '14.x'                # set this to the node version to use

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Trust Certificate
      run: |
        sudo apt-get install expect
        certPath="$GITHUB_WORKSPACE/Certificates/aspnetapp-root-cert.pfx"
        password="password"

        # Use expect to automate the passphrase input
        expect -c "
        spawn openssl pkcs12 -in \"$certPath\" -clcerts -nokeys -out certificate.crt -password pass:\"$password\"
        expect \"Enter Import Password:\" { send \"$password\n\" }
        expect eof
        "

        expect -c "
        spawn openssl pkcs12 -in \"$certPath\" -nocerts -out private.key -password pass:\"$password\"
        expect \"Enter Import Password:\" { send \"$password\n\" }
        expect eof
        "

        sudo cp certificate.crt /usr/local/share/ca-certificates/aspnetapp-root-cert.crt
        sudo update-ca-certificates

        sudo cp private.key /etc/ssl/private/aspnetapp-root-cert.key
        sudo chmod 400 /etc/ssl/private/aspnetapp-root-cert.key    
            
    - name: Build Docker Image
      run: docker build . --file EstateManagementUI/Dockerfile --tag estatemanagementui:latest

    - name: Restore Nuget Packages
      run: dotnet restore EstateManagementUI.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }}

    - name: Run Integration Tests (Firefox)
      env:
        Browser: Firefox
        IsCI: true
      run: dotnet test "EstateManagementUI.IntegrationTests\EstateManagementUI.IntegrationTests.csproj" --filter Category=PRTest
      
    - uses: actions/upload-artifact@v4.4.0
      if: ${{ failure() }}
      with:
        name: firefoxtracelogs
        path: /home/txnproc/trace/   

  codecoverage:
    name: "Nightly Build - Code Coverage"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Restore Nuget Packages
      run: dotnet restore EstateManagementUI.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }}

    - name: Build Code
      run: dotnet build EstateManagementUI.sln --configuration Release

    - name: Run Unit Tests
      run: |
        echo "ASPNETCORE_ENVIRONMENT are > ${ASPNETCORE_ENVIRONMENT}"
        dotnet test "EstateManagementUI.BusinessLogic.Tests\EstateManagementUI.BusinessLogic.Tests.csproj" /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:ExcludeByAttribute="Obsolete" /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByAttribute="CompilerGeneratedAttribute" /p:ExcludeByAttribute="ExcludeFromCodeCoverageAttribute" /p:CoverletOutput="../lcov1.info" /maxcpucount:1 /p:CoverletOutputFormat="lcov"
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4 
      with:
          token: ${{ secrets.CODECOV_TOKEN }} 
          files: ./lcov1.info
